# Generated by Django 3.2.8 on 2022-09-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
