# Generated by Django 3.2.8 on 2022-09-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='charge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
