# Generated by Django 3.2.8 on 2022-09-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_payment_charge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
    ]
