# Generated by Django 3.2.8 on 2022-09-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_order_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CARD', 'Card'), ('CASH', 'Cash')], default='CARD', max_length=10),
            preserve_default=False,
        ),
    ]
