# Generated by Django 3.2.8 on 2022-09-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20220921_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-ordered_date',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-update_on',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='user',
            new_name='buyer',
        ),
    ]
